LoginRegistration/Models/Post.cs
// Disabled because we know the framework will assign non-null values when it
// constructs this class for us.
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoginRegistration.Models;

// [NotMapped] taghelper will define a class/property to not be stored in your db
public class Post
{
    [Key]
    public int PostId { get; set; }

    [Required(ErrorMessage = "is required")]
    [MinLength(2, ErrorMessage = "must be at least 2 characters")]
    [MaxLength(45, ErrorMessage = "must be shorter than 45 characters")]
    [Display(Name = "Favorite Topic")]
    public string Topic { get; set; }

    [Required(ErrorMessage = "is required")]
    [MinLength(2, ErrorMessage = "must be at least 2 characters")]
    public string Body { get; set; }

    [Display(Name = "Image URL")]
    public string? ImgUrl { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;



    /*************************************************************************
    Relationship properties below

    Foreign Keys: id of a different (foreign) model
    
    Navigation Props:
        data type is a related model
        Must use the .Include for the nav prop

    *************************************************************************/

    public int UserId { get; set; } // this FK Needs to match w/ the PK property
    public User? Author { get; set; }

    // this must have a default value of an empty list because when we look through this list with a foreach loop, it will break if the List = null, but it can look through an empty list without breaking
    public List<UserPostLike> Likes { get; set; } = new List<UserPostLike>();
}

LoginRegistration/Controllers/PostController.cs
// Using statements
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LoginRegistration.Models;
using Microsoft.EntityFrameworkCore;

namespace LoginRegistration.Controllers;
    
public class PostController : Controller
{
    

    // _context is just a variable name, can be called anything (e.g. DATABASE, db, _db, etc)
    private EFLectureContext _context;

    private int? uid
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }
     
    // here we can "inject" our context service into the constructor
    public PostController(EFLectureContext context)
    {
        _context = context;
    }

    [HttpGet("/posts/all")]
    public IActionResult All()
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        List<Post> AllPosts = _context.Posts
        .Include(post => post.Author)
        // line below was to get author post count on post tile (BAD USE CASE)
        // .ThenInclude(author => author.CreatedPosts)
        .Include(post => post.Likes)
        .ToList();

        return View("All", AllPosts);
    }

    [HttpGet("/posts/new")]
    public IActionResult New()
    {
        int? userId = HttpContext.Session.GetInt32("UUID");
        if (userId == null)
        {
            return RedirectToAction("Index", "User");
        }

        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        return View("New");
    }

    [HttpPost("/posts/create")]
    public IActionResult Create(Post newPost)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        if (ModelState.IsValid == false) {
            // by not defaulting the return of View() in New, we can invoke the New() function & not have to re-write code
            // return View("New");

            return New();
        }

        if (uid != null)
        {
            newPost.UserId = (int)uid;
        }

        //this only runs if ModelState.IsValid == true
        _context.Posts.Add(newPost);
        // our sql database doesn't update until we save changes
        // after calling SaveChanges, our newPost will now have a value stored in PostId that was automatically generated by our database
        _context.SaveChanges();

        return RedirectToAction("All");
    }

    [HttpGet("/posts/{postId}")]
    public IActionResult ViewPost(int postId)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        // since firstordefault can return a single post, or null. our variable needs to be a nullable datatype
        Post? post = _context.Posts
            .Include(p => p.Author)
            .Include(p => p.Likes)
            // .ThenInclude is used for including something on the
            // object that was JUST included (for this example, our likes list)
            .ThenInclude(like => like.User)
            .FirstOrDefault(post => post.PostId == postId);
        
        // to get rid of "object might be null" warnings, write a conditional that checks for it & returns if it's null
        if (post == null)
        {
            return RedirectToAction("All");
        }
        
        return View("ViewPost", post);
    }

    [HttpPost("/posts/{deletedPostId}/delete")]
    public IActionResult Delete(int deletedPostId)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        Post? postToBeDeleted = _context.Posts.FirstOrDefault(post => post.PostId == deletedPostId);

        if (postToBeDeleted != null)
        {
            if(postToBeDeleted.UserId == uid)
            {
                _context.Posts.Remove(postToBeDeleted);
                _context.SaveChanges();
            }
        }

        return RedirectToAction("All");
    }

    [HttpGet("/posts/{postToBeEdited}/edit")]
    public IActionResult EditPost(int postToBeEdited)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        Post? post = _context.Posts.FirstOrDefault(post => post.PostId == postToBeEdited);

        if (post == null || post.UserId != uid)
        {
            return RedirectToAction("All");
        }

        return View("Edit", post);
    }


    [HttpPost("/posts/{updatedPostId}/update")]
    public IActionResult UpdatePost(int updatedPostId, Post updatedPost)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        if (ModelState.IsValid == false)
        {
            // can remove all of the code below as long as we don't default our View() function in EditPost

            // Post? originalPost = _context.Posts.FirstOrDefault(post => post.PostId == updatedPost.PostId);
            // if (originalPost == null)
            // {
            //     RedirectToAction("All");
            // }
            // return View("Edit", originalPost);

            return EditPost(updatedPostId);
        }

        Post? dbPost = _context.Posts.FirstOrDefault(post => post.PostId == updatedPostId);

        if (dbPost == null || dbPost.UserId != uid)
        {
            return RedirectToAction("All");
        }

        dbPost.Topic = updatedPost.Topic;
        dbPost.Body = updatedPost.Body;
        dbPost.ImgUrl = updatedPost.ImgUrl;
        dbPost.UpdatedAt = DateTime.Now;

        _context.Posts.Update(dbPost);
        _context.SaveChanges();

        return RedirectToAction("ViewPost", new { postId = dbPost.PostId });
    }

    [HttpPost("/posts/{pId}/like")]
    public IActionResult Like(int pId)
    {
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Index", "User");
        }

        UserPostLike? existingLike = _context.UserPostLikes.FirstOrDefault(like => like.PostId == pId && like.UserId == uid);

        if (existingLike == null)
        {
            UserPostLike newLike = new UserPostLike(){
                PostId = pId,
                UserId = (int)uid
            };
            _context.UserPostLikes.Add(newLike);
        }
        else
        {
            _context.Remove(existingLike);
        }


        _context.SaveChanges();
        return RedirectToAction("All");
    }
 }

LoginRegistration/Views/Post/All.cshtml
@model List<Post>
<h3>Welcome @Context.Session.GetString("Name"), UUID: @Context.Session.GetInt32("UUID")</h3>

<h1>Come view our posts!!</h1>


@* 
    You can use a partial that requires a different ViewModel
        by creating an instance of that model
        and passing it into your partial under the tag model="" 
*@

@{
    Post newPost = new Post();
    @* newPost.Topic = "topic created in cshtml file"; *@
}
<partial name="_New" model="@newPost"></partial>

@foreach (Post post in Model)
{
    <div class="card shadow rounded mx-auto w-75 mb-3">
        <h4 class="card-title text-center bg-dark text-light py-2 rounded-top">
        @post.Topic
        </h4>

        <div class="card-body">
        <p class="card-text">@post.Body</p>
        <small class="text-muted"> Submitted on: @post.CreatedAt </small>
        </div>

        @if(post.Author != null)
        {
            <p>@post.Author.FullName()</p>
            @* Code below only runs when you use .ThenInclude for your author to
            also include their created posts. (BUT THIS IS A BAD USE CASE)
            <span>has written @post.Author.CreatedPosts.Count posts</span> *@
        }

        @if (post.ImgUrl != null && post.ImgUrl != "") {
            <img src="@post.ImgUrl" alt="related to post." class="card-img-bottom" />
        }
        <a 
            asp-action="ViewPost"
            asp-route-postId="@post.PostId"
        >View Details</a>

        <a href="/posts/@post.PostId" >View But w/ href</a>

        @{
            bool alreadyLiked = post.Likes.Any(like => like.UserId == Context.Session.GetInt32("UUID"));
        }

        <div class="card-footer text-center">
            <form asp-controller="Post" asp-action="Like" asp-route-pId="@post.PostId" method="POST">
                <button>
                    @if (alreadyLiked)
                    {
                        <span>Unlike</span>
                    }
                    else
                    {
                        <span>Like</span>
                    }
                </button>
            </form>
            <span>Likes: @post.Likes.Count</span>
        </div>
    </div>
}

LoginRegistration/Views/Post/Edit.cshtml
@model Post

<div class="container w-75 mx-auto">
  <h2 class="text-center">Edit Post</h2>

  <form class="shadow p-3 rounded" asp-controller="Post" asp-action="UpdatePost" asp-route-updatedPostId="@Model.PostId" method="POST">
    <div class="mb-3">
      <label asp-for="Topic"></label>
      <span asp-validation-for="Topic" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Topic" value="@Model.Topic">
    </div>

    <div class="mb-3">
      <label asp-for="Body"></label>
      <span asp-validation-for="Body" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Body" value="@Model.Body">
    </div>

    <div class="mb-3">
      <label asp-for="ImgUrl"></label>
      <input class="form-control" asp-for="ImgUrl" value="@Model.ImgUrl">
    </div>

    <button class="btn btn-success">Submit</button>
  </form>
</div>

LoginRegistration/Views/Post/ViewPost.cshtml
@model Post

<h1><label asp-for="Topic"></label>:  @Model.Topic</h1>
@if(Model.Author != null)
{
<h3>Written by: @Model.Author.FullName()</h3>
}
<h3>@Model.Body</h3>
<img src="@Model.ImgUrl" alt="related to post." class="card-img-bottom" />

<h3>Users who like this post:</h3>
@foreach (UserPostLike like in Model.Likes)
{
    if(like.User != null)
    {
        <p>@like.User.FullName()</p>
    }
}

<br><br>

@if (@Model.UserId == Context.Session.GetInt32("UUID"))
{
    <a href="/posts/@Model.PostId/edit">Edit this post</a>

    <form
        asp-controller="Post"
        asp-action="Delete"
        asp-route-deletedPostId="@Model.PostId"
        method="POST"
        >
        <button>Delete</button>
    </form>
}

LoginRegistration/Views/Post/_New.cshtml
@model Post

<div class="container w-75 mx-auto">
  <h2 class="text-center">New Post</h2>

  @* <form href="posts/create" method="POST"> *@
  <form class="shadow p-3 rounded" asp-controller="Post" asp-action="Create" method="POST">
    
    <div class="mb-3">
      <label asp-for="Topic"></label>
      <span asp-validation-for="Topic" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Topic">
    </div>

    <div class="mb-3">
      <label asp-for="Body"></label>
      <span asp-validation-for="Body" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Body">
    </div>

    <div class="mb-3">
      <label asp-for="ImgUrl"></label>
      <input class="form-control" asp-for="ImgUrl">
    </div>

    <button class="btn btn-success">Submit</button>
  </form>
</div>